spring:
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: ${JDBC_USER}
    password: ${JDBC_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  #Секреты не должны храниться в открытом виде!
  secret: BarsukovDmirtiyVladimirovichBKS2201000
  expiration: 5000000